FROM ruby:3.3.7-slim

# Install essential Linux packages
RUN apt-get update -qq && \
    apt-get install -y build-essential libvips pkg-config sqlite3 git libyaml-dev

# Set working directory
WORKDIR /app

# Set development environment
ENV RAILS_ENV=development

# Copy Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

# Copy the rest of the application
COPY . .

# Fix line endings
RUN find . -type f -exec sed -i 's/\r$//' {} +

# Setup the database
RUN rails db:create db:migrate

EXPOSE 3000

# Start the server
CMD ["rails", "server", "-b", "0.0.0.0"] 