require 'twilio-ruby'

TWILIO_ACCOUNT_SID = ENV['TWILIO_ACCOUNT_SID'] || ''
TWILIO_AUTH_TOKEN = ENV['TWILIO_AUTH_TOKEN'] || ''
TWILIO_WHATSAPP_NUMBER = ENV['TWILIO_WHATSAPP_NUMBER'] || ''
TWILIO_PHONE_NUMBER = ENV['TWILIO_PHONE_NUMBER'] || ''